#!/bin/bash

# AwesomeTTS text-to-speech add-on for Anki
#
# Copyright (C) 2010-2013  Anki AwesomeTTS Development Team
# Copyright (C) 2010-2012  Arthur Helfstein Fragoso
# Copyright (C) 2013       Dave Shifflett
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# generate python files based on the designer ui files. pyuic4 and pyrcc4
# should be on the path.

if [ ! -d "designer" ]
then
    echo "Please run this from the project root"
    exit
fi

topath=forms

mkdir -p $topath

init=$topath/__init__.py
temp=$topath/scratch
rm -f $init $temp
echo "# This file auto-generated by build_ui.sh. Don't edit." > $init
echo "__all__ = [" >> $init

echo "Generating forms.."
for i in designer/*.ui
do
    base=$(basename $i .ui)
    py="$topath/${base}.py"
    echo "	\"$base\"," >> $init
    echo "import $base" >> $temp
    if [ $i -nt $py ]; then
        echo " * "$py
        pyuic4 $i -o $py
        # munge the output to use gettext
        perl -pi.bak -e 's/QtGui.QApplication.translate\(".*?", /_(/; s/, None, QtGui.*/))/' $py
        rm $py.bak
    fi
done
echo "]" >> $init
cat $temp >> $init
rm $temp

echo "Building resources.."
#pyrcc4 designer/icons.qrc -o $topath/icons_rc.py
